version: '3.9'

services:
  redis-1:
    image: redis:7.0.5-alpine
    hostname: redis-1
    ports:
      - 6379:6379
    healthcheck:
      test: redis-cli ping
      interval: 3s
      timeout: 5s
      retries: 5
  rabbitmq-1:
    image: rabbitmq:3.9.21-management-alpine
    hostname: rabbitmq-1
    container_name: rabbitmq-1-container
    ports:
      - 5672:5672
      - 15672:15672
      - 25672:25672
    volumes:
      - ./rabbitmq/rabbitmq-1/:/etc/rabbitmq/conf.d/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
  go-stack-questions:
    build:
      context: ./go.stack-questions/
      dockerfile: Dockerfile
    container_name: go-stack-questions-container
    env_file:
      - ./go.stack-questions/.env
    environment:
      - RABBITMQ_HOST=rabbitmq-1
    restart: on-failure
    links:
      - rabbitmq-1
  py-deduplicator:
    build:
      context: ./py.deduplicator/
      dockerfile: Dockerfile
    container_name: py-deduplicator-container
    env_file:
      - ./py.deduplicator/.env
    environment:
      - RABBITMQ_HOST=rabbitmq-1
      - REDIS_HOST=redis-1
    restart: on-failure
    links:
      - rabbitmq-1
      - redis-1